# Generated by Django 5.2.8 on 2025-11-22 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название бизнеса/Имя мастера')),
                ('description', models.TextField(blank=True, verbose_name='О себе')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено админом')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('category', models.CharField(choices=[('barber', 'Barbershop'), ('nails', 'Nail Salon'), ('brows', 'Eyebrows & Lashes'), ('medical', 'Medical Center'), ('dentist', 'Dentist'), ('psycho', 'Psychotherapy'), ('shop', 'Shops'), ('auto', 'Auto Service'), ('spa', 'Spa Salon'), ('pets', 'Pet Services')], default='barber', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Длительность (мин)')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.businessprofile')),
            ],
        ),
    ]
