# Generated by Django 5.2.8 on 2025-11-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(default='09:00', verbose_name='Начало работы')),
                ('end_time', models.TimeField(default='18:00', verbose_name='Конец работы')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='Выходной')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='core.businessprofile')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('master', 'day_of_week')},
            },
        ),
    ]
