# Generated by Django 5.2.8 on 2025-11-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='category',
            field=models.CharField(choices=[('barber', 'Barbershop'), ('nails', 'Nail Salon'), ('brows', 'Eyebrows & Lashes'), ('medical', 'Medical Center'), ('dentist', 'Dentist'), ('psycho', 'Psychotherapy'), ('shop', 'Shops'), ('auto', 'Auto Service'), ('spa', 'Spa Salon'), ('pets', 'Pet Services')], default='barber', max_length=50, verbose_name='Категория салона'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название бизнеса'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='is_day_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
